name: terraform-validate
description: Validate a terraform configuration directory.

#triggers event on push to main (or set to trigger on pull request and you can define which branch).


runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /scripts/validate.sh

#jobs:

#  build:
#    runs-on: ubuntu-20.04
#    steps:
   
#      - name: Check Out Repo 
#        uses: actions/checkout@v2
   
#      - name: Setup & Validate
#        uses: adminrl/tf-validate@v1.1
#        with:
#          context: ./
 #         file: ./Dockerfile
      

#jobs: Run Validate
#  inputs:
#    path:
#      description: Path to the terraform configuration
#      required: true

#runs:
#  using: docker
#  image: ../image/Dockerfile-base
#  entrypoint: /entrypoints/validate.sh
