name: terraform-validate
#description: Validate a terraform configuration directory

on: push 
#triggers event on push (or pull and you can define which branch)

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
   
      - name: Check Out Repo 
        uses: actions/checkout@v2
   
      - name: Setup & Validate
        run:  tf-validate/image/Dockerfile 
      

#jobs: Run Validate
#  inputs:
#    path:
#      description: Path to the terraform configuration
#      required: true

#runs:
#  using: docker
#  image: ../image/Dockerfile-base
#  entrypoint: /entrypoints/validate.sh
